# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'NET45-Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Castle.Facilities.NHibernateIntegration nuspec'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src'
    Contents: '**\*.nuspec'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Castle.Facilities.NHibernateIntegratio build output'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Castle.Facilities.NHibernateIntegration\bin\NET45-Release'
    Contents: '**\Castle.Facilities.NHibernateIntegration.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Castle.Facilities.NHibernateIntegration\build-output'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Castle.Facilities.NHibernateIntegration Source Code'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Castle.Facilities.NHibernateIntegration'
    Contents: '**\*.cs'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Castle.Facilities.NHibernateIntegration\src'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'